services:
  ui:
    image: ghcr.io/scottmaran/lux-ui:${LUX_VERSION}
    volumes:
      - ${LUX_LOG_ROOT:-./logs}:/logs:ro
      - ${LUX_LOG_ROOT:-./logs}:/logs_rw:rw
      - ${LUX_RUNTIME_DIR:-./runtime}:/run/lux/runtime:rw
    group_add:
      - "${LUX_RUNTIME_GID:-0}"
    environment:
      - UI_LOG_ROOT=/logs
      - UI_LOG_ROOT_RW=/logs_rw
      - UI_RUNTIME_CONTROL_PLANE_SOCKET=/run/lux/runtime/control_plane.sock
    ports:
      - "127.0.0.1:8090:8090"
