export const colors = {
  terminalBg: '#1E1E2E',
  terminalText: '#CDD6F4',
  terminalGreen: '#A6E3A1',
  terminalYellow: '#F9E2AF',
  terminalRed: '#F38BA8',
  terminalCyan: '#7DD3FC',
  terminalCursor: '#CDD6F4',
  overlayBg: 'rgba(0, 0, 0, 0.80)',
  overlayText: '#FFFFFF',
  dashboardBg: '#F9FAFB',
  accentGreen: '#22C55E',
  accentPurple: '#A855F7',
  accentBlue: '#3B82F6',
  brandText: '#FFFFFF',
  taglineText: '#9CA3AF',
  darkBg: '#111827',
  darkerBg: '#0F0F1A',
} as const;
